package com.ftn.sbnz.service.model;

public enum Trait {
    ADMIN, ANIMA_SQUAD, GADGETEEN, INFINITEAM, LASERCORPS, MECHA, OX_FORCE, RIFTWALKER, STAR_GUARDIAN, SUPERS, THREAT, ACE, AEGIES, BRAWLER, DEFENDER, DUELIST, HACKER, HEART, MASCOT, PRANKSTER, RENEGADE, SPELLSLINGER
}
