package rules;

import com.ftn.sbnz.service.model.event.AugmentEvent;
import com.ftn.sbnz.service.model.Game;
import com.ftn.sbnz.service.model.Composition;
import com.ftn.sbnz.service.model.Component;
import com.ftn.sbnz.service.model.Augment;
import com.ftn.sbnz.service.model.Carry;
import com.ftn.sbnz.service.service.RuleService;
import java.util.Map
import java.util.List;

global RuleService ruleService;

rule "Hello"
    when
        eval(5 > 3);
    then
        System.out.println("Hello world!");
end

rule "AugmentChoice"
no-loop
    when
        $currentGame: Game($augment1: augmentChoice.get(0), $augment2: augmentChoice.get(1), $augment3: augmentChoice.get(2), username == "test", phase == 0)
        $aug1: Number() from accumulate(
            $e1: AugmentEvent(name == $augment1.getName())
            over window:time(20s),
            count($e1)
        )
        $aug2: Number() from accumulate(
            $e2: AugmentEvent(name == $augment2.getName())
            over window:time(20s),
            count($e2)
        )
        $aug3: Number() from accumulate(
            $e3: AugmentEvent(name == $augment3.getName())
            over window:time(20s),
            count($e3)
        )
    then
        int index;
        $aug1 = ruleService.getAugmentCompositionConnection($augment1, $currentGame.getComposition()) * $augment1.getAveragePlace() / ($aug1.intValue() * 0.5 + 1);
        $aug2 = ruleService.getAugmentCompositionConnection($augment2, $currentGame.getComposition()) * $augment2.getAveragePlace() / ($aug2.intValue() * 0.5 + 1);
        $aug3 = ruleService.getAugmentCompositionConnection($augment3, $currentGame.getComposition()) * $augment3.getAveragePlace() / ($aug3.intValue() * 0.5 + 1);
        System.out.println($aug1 + " " + $aug2 + " " + $aug3);
        if ($aug1.intValue() >= $aug2.intValue() && $aug1.intValue() >= $aug3.intValue()) {
            index = 1;
        } else if ($aug2.intValue() >= $aug1.intValue() && $aug2.intValue() >= $aug3.intValue()) {
            index = 2;
        } else {
            index = 3;
        }
        modify($currentGame) {
            addAugment($currentGame.getAugmentChoice().get(index))
        };
        modify($currentGame) {
            setPhase(1)
        };
end

rule "CompositionUpdate"
no-loop
when
    $currentGame: Game(username == "test", phase == 1)
then
    Composition comp = null;
    Double maxValue = (double) -1;
    for (Map.Entry<Composition, Double> entry : $currentGame.getCompValue().entrySet()){
        modify($currentGame) {
            addCompValue(entry.getKey(), entry.getValue()/2 +
            (ruleService.getAugmentCompositionConnection($currentGame.getAugments().get($currentGame.getAugments().size() - 1)
            ,entry.getKey()) / 2))
        };
        if(entry.getValue() > maxValue){
            maxValue = entry.getValue();
            comp = entry.getKey();
        }
    };
    System.out.println($currentGame.getAugments().get($currentGame.getAugments().size() - 1).getName() + " " +comp.getName() + " " + maxValue);
    modify($currentGame) {
        setComposition(comp)
    };
    modify($currentGame) {
        setPhase(2)
    };
end

rule "ChampionsForComposition"
no-loop
when
    $currentGame: Game(username == "test", phase == 2)
then
    System.out.println("set Carry");
    insert(new Carry($currentGame.getComposition().getCarry().getName(), $currentGame.getId(), $currentGame.getUsername(), false));
    modify($currentGame) {
        setPhase(3)
    };
end

rule "GenerateCarry"
no-loop
when
    $carry: Carry(username == "test")
    $currentGame: Game(username == "test", phase == 3)
    eval($currentGame.getComponents().size() > 0)
then
    List<Component> missingComponents = ruleService.getMissingComponents($carry, $currentGame.getComponents());
    System.out.println("You are missing: ");
    for(Component component : missingComponents){
        System.out.println(component.getName());
    }
    modify($currentGame) {
        setPhase(4)
    };
end